### ISSUE TITLE
Fix layout issues on IE11

### ISSUE THREAD

**Issue by tempertemper** [tempertemper/tempertemper.net#598]

**Comment by tempertemper** [comment]
A useful-looking [Stack Overflow post on targeting IE11 only](https://stackoverflow.com/questions/18907131/detecting-ie11-using-css-capability-feature-detection), to undo the negative margin styling for full-width elements using:

```css
_:-ms-fullscreen, :root .ie11up { property:value; }
```
