### ISSUE TITLE
Enhance button styling

### ISSUE THREAD

**Issue by tempertemper** [tempertemper/tempertemper.net#816]
Add some extra styling to the `<button>` mixin to add a darker line to the bottom:

```scss
.button {
  box-shadow: 0 3px $line-colour;

  :active {
    box-shadow: none;
  }
}
```

where `$line-colour` is `$colour-primary-darker` (`#0077b3`) in light mode and `#006394` in dark mode (a new `$colour-dark-mode-primary-darker` variable will have to be added for this).

Also:

- take a couple of pixels of bottom padding from the button
- reduce the left and right padding of the buttons

```
padding: .5em 1em calc(..5em = 3px);
```
